# Generated by Django 4.0.4 on 2023-03-01 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='tb_category',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='tb_publisher',
        ),
    ]
