# Generated by Django 4.0.4 on 2023-03-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ISBN', models.CharField(max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='api.category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publisher', to='api.publisher')),
            ],
        ),
    ]
