# Generated by Django 4.0.4 on 2023-03-01 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='tb_book',
        ),
    ]
