# Generated by Django 4.0.4 on 2023-03-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelTable(
            name='purchase',
            table='tb_purchase',
        ),
    ]
