# Generated by Django 4.0.4 on 2023-03-01 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_purchase_options_alter_purchase_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amout', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='api.book')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.purchase')),
            ],
            options={
                'verbose_name': 'Item_Purchase',
                'verbose_name_plural': 'Itens_Purchases',
                'db_table': 'tb_item_purchase',
            },
        ),
    ]
