# Generated by Django 4.0.4 on 2023-03-06 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_itempurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempurchase',
            old_name='amout',
            new_name='amount',
        ),
    ]
