version: "3.9"
   
services:
  web:
    build: ./web
    image: library_api:2.1
    container_name: library_api_backend
    env_file: .env
    command: uwsgi --socket :8000 --master --enable-threads --protocol=http  --module web.wsgi
    restart: always
    ports:
      - 8000:8000 
